#!/usr/bin/python3

# tests/test_base_module.py

import unittest

from src.my_module import MyClass, my_function


class TestMyModule(unittest.TestCase):
    def test_my_class(self):
        my_instance = MyClass()
        self.assertIsInstance(my_instance, MyClass)

    def test_my_function(self):
        result = my_function()
        self.assertIsInstance(result, int)


if __name__ == "__main__":
    unittest.main()
